### ISSUE TITLE
Intresting Problem about antivirus software

### ISSUE THREAD

**Issue by 827Dream** [nefarius/Injector#15]
Hi,I've been using this tool you wrote recently, it's very useful，but i find an intresting problem , 
I compiled it myself (just x64)will be killed by antivirus software(trend)，
Did not modify any options other than modifying to treat warnings as errors，but the version you publish won't be killed😄
![image](https://user-images.githubusercontent.com/52020508/181216757-9a97d914-71da-4b12-ac6b-4cda9e3915a8.png)

![image](https://user-images.githubusercontent.com/52020508/181217512-e9786296-1441-4228-94b2-efd7f2aeb08f.png)

so im very curious about this，maybe it has something to do with the compilation environment or options? I didn't modify any code after all

Can you be specific about your build environment and options?so that I can reproduce

**Comment by nefarius** [comment]
Most probably heuristics. Since my binaries have been circled for quite some years now their signature is probably deemed "safe", don't worry, it happened to me a few times too, I built something locally, AV quarantined it. Rebuilt with no changes, suddenly everything is fine. A side effect of AV, I have no real answer for I'm afraid.

My build environment is just bare bone Visual Studio 2019 with the C/C++ workload installed.
