### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by memerich** [nefarius/Injector#9]
I getting this error "Call to LoadLibraryW in remote process failed."

**Comment by nefarius** [comment]
Make sure you inject a 32-Bit DLL in a 32-Bit process and likewise for 64-Bit. The DLL you inject must also have all its possible dependencies already mapped into the process, that's basically it. It works best if the DLL is self contained (has all dependencies statically linked into it). Good luck!

**EDIT:** depending on the use-case if you inject into games, make sure they are not anti-cheat protected, since most sophisticated solutions block DLL injection.
